---
- hosts: all
  gather_facts: no
  
  tasks:
  -  name: get free space
     win_shell: "Get-PSDrive C | Select-Object Free | ConvertTo-Json"
     register: free_space_before_cleanup
    
  -  debug:
      msg: "Free space before cleanup: {{ ((free_space_before_cleanup.stdout | from_json)['Free']|int*10 / (1024*1024*1024)) | round(2, 'floor') }} GB"
      
  -  name: delete file
     win_find: 
      paths: C:\Users\ansible\Desktop\Test
      patterns: ['*.txt']
     register: delete_file
      
  -  name: remove files
     win_file:
      path: “{{ item.path }}”
      state: absent
     with_items: 
       -  “{{ delete_file.files }}”
     
  -  name: get free space
     win_shell: "Get-PSDrive C | Select-Object Free | ConvertTo-Json"
     register: free_space_after_cleanup
     
  -  debug:
      msg: "free_space_after_cleanup: {{ ((free_space_before_cleanup.stdout | from_json)['Free']|int*10 / (1024*1024*1024)) | round(2, 'floor') }} GB"     
