---
- hosts: all

  tasks:
  -  name: get free space
     win_shell: Get-PSDrive C | Select-Object Free | ConvertTo-Json
      register: free_space_before_cleanup
          
  -  name: get free space
     win_shell: Get-PSDrive C | Select-Object Free | ConvertTo-Json
      register: free_space_after_cleanup
      
  -  debug:
     msg:
      - "Free space before cleanup:  {{ ((free_space_before_cleanup.stdout | from_json)['Free']|int / (1024*1024*1024)) | round(2, 'floor') }} GB"
      - "Free space after cleanup: {{ ((free_space_after_cleanup.stdout | from_json)['Free']|int / (1024*1024*1024)) | round(2, 'floor') }} GB"
