---
- hosts: all
  gather_facts: no
  vars:
    path: 'C:\Users\ansible\Desktop\Test'
  
  tasks:
    - name: get free space
      win_shell: "Get-PSDrive C | Select-Object Free | ConvertTo-Json"
      register: free_space_before_cleanup
    
    - debug:
        msg: "Free space before cleanup: {{ ((free_space_before_cleanup.stdout | from_json)['Free']|int*10 / (1024*1024*1024)) | round(2, 'floor') }} GB"
      
    - name: delete file from folder
      win_find: 
        paths: "{{ path }}"
        patterns: ['*.txt']
        file_type: file
        recurse: true
      register: files
    - debug:
        msg: "{{ files.files[0].filename }}"
      
#  - name: Set fact
#    set_fact:
#      file_name: "{{ files }}"
     
    - name: remove files
      win_file:
        path: “{{ item }}”
        state: absent
      loop: 
        - “{{ path }}/”
     
    - name: get free space
      win_shell: "Get-PSDrive C | Select-Object Free | ConvertTo-Json"
      register: free_space_after_cleanup
     
    - debug:
        msg: "free_space_after_cleanup: {{ ((free_space_before_cleanup.stdout | from_json)['Free']|int*10 / (1024*1024*1024)) | round(2, 'floor') }} GB"     
