---
- name: tasks file for ansible-role-windows-msiuninstall
  hosts: all
  
  tasks:
    # - name: Uninstall an MSI file
    #   win_msi:
    #     path: "{{msi_path}}"
    #     state: absent
    #   when: msi_path is defined and msi_path != ""
    - name: Remove a .msp patch
      ansible.windows.win_package:
        product_id: 7-Zip
        arguments: /S
        state: absent
    #  when: product_id is defined and product_id != ""
