---

#- name: tasks file for ansible-role-windows-msiuninstall
#  hosts: all
#  tasks:
become_method: runas
become: yes
become_user: ansible
- name: Uninstall an MSI file
  win_msi:
    path: "{{msi_path}}"
    state: absent
  when: msi_path is defined and msi_path != ""     
- name: Remove a .msp patch
  win_package:
#    path: C:\Program Files\7-Zip\Uninstall.exe
    product_id: "{{product_id}}"
    # arguments: 
    # - /s
    # - /qn
    state: absent
  when: product_id is defined and product_id != ""
  # become_method: runas
  # become: yes
  # become_user: ansible